# Generated by Django 3.2.8 on 2022-02-13 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenon', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.FloatField(default=0)),
                ('contenue', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress_text', models.CharField(max_length=200)),
                ('numero_gsm', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Bordereau2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pu', models.IntegerField(default=0)),
                ('qte', models.IntegerField(default=0)),
                ('qte2', models.IntegerField(default=0)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.produits')),
            ],
        ),
        migrations.CreateModel(
            name='Bordereau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pu', models.IntegerField(default=0)),
                ('qte', models.IntegerField(default=0)),
                ('qte2', models.IntegerField(default=0)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.produits')),
            ],
        ),
    ]
