# Generated by Django 3.2.8 on 2022-02-13 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produits',
            new_name='Produit',
        ),
        migrations.RemoveField(
            model_name='bordereau',
            name='qte2',
        ),
        migrations.DeleteModel(
            name='Bordereau2',
        ),
    ]
