# Generated by Django 3.2.8 on 2022-02-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20220213_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='confirmation',
            field=models.IntegerField(default=0),
        ),
    ]
