# Generated by Django 3.2.8 on 2022-02-20 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0003_commande_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='adress_text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='numero_gsm',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
