# Generated by Django 3.2.8 on 2022-02-20 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20220220_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordereau',
            name='commande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.commande'),
        ),
    ]
